### ISSUE TITLE
X-Forwarded-For with multiple IPs

### ISSUE THREAD

**Issue by dbeja** [ithemes/iThemes-Security#123]
I think you have a bug in getIp() function.

You are validating if the X-Forwared-For header is a valid IP, but if the server has some proxies or load balancers, you will have multiple IPs in this field, starting with the original client and then the following proxies.

So, if someone is banned in a server like this, X-Forward-For will not validate, and instead the IP of the proxy (REMOTE ADDRESS) will be banned, and the site will be down to everyone.

I think it would be more correct if you get the first IP of the X-Forwared-For before validating it.

Do you want me to pull a request?

**Comment by soupdiver** [comment]
ehm running into the same... any updates?

**Comment by wiliame** [comment]
A workaround:

```
add_filter('itsec_filter_remote_addr_headers', function($headers) {
    if(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $ips = preg_split('/\s*,\s*/', $_SERVER['HTTP_X_FORWARDED_FOR'], -1, PREG_SPLIT_NO_EMPTY);
        
        if($ips) {
            $_SERVER['HTTP_ITHEMES_REAL_IP'] = $ips[0];
            array_unshift($headers, 'HTTP_ITHEMES_REAL_IP');
        }
    }
    
    return $headers;
});
```
