### ISSUE TITLE
Add X-Frame-Options

### ISSUE THREAD

**Issue by espellcaste** [ithemes/iThemes-Security#131]
I haven't found any option to allow the proper X-Frame-Options. It could improve security a little bit.

More backgroud:

https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options
https://blog.mozilla.org/security/2013/12/12/on-the-x-frame-options-security-header/
http://kb.sucuri.net/warnings/hardening/headers-x-frame-clickjacking

**Comment by aaroncampbell** [comment]
Just dropping by here to say that WordPress already does this for all admin and login pages since about 4 years ago. See:
https://core.trac.wordpress.org/ticket/12293
https://core.trac.wordpress.org/changeset/17826

Are you looking for a way to do this for the front end of your site?

**Comment by espellcaste** [comment]
@aaroncampbell Interesting! I didn't know that! 

In the front-end also would be interesting. Don't you agree?

**Comment by aaroncampbell** [comment]
I don't know that SAMEORIGIN is all that useful in general on the front end. Maybe for certain sites, ecommerce or the like, but there're actually a lot of situations where allowing your site to be embedded in a frame somewhere makes a lot of sense.

Also, I'm pretty sure that [frame-ancestors](https://w3c.github.io/webappsec/specs/content-security-policy/#directive-frame-ancestors) is supposed to take the place of the x-frame-options directive, although I'd need to research that a little more.

**Comment by espellcaste** [comment]
@aaroncampbell thanks for the info. I'm sorry for my lack of deeper knowledge about the use of X-Frame. At first I thought the website without it would make it easier to the hacker to hack. =)

But it seem as you mentioned that it is indeed useful in some cases and maybe it is not a great idea as an option in iThemes Security.

Thanks for the feedback!
